### ISSUE TITLE
Potential missing subject_id: JOUR?

### ISSUE THREAD

**Issue by skylineproject** [umn-asr/courses#45]
Hey all,

I tested out the API using some of the courses I'm currently taking. I noticed that Journalism/Mass Comm. classes (subject_id=JOUR) do not seem to show up -- I'm getting an empty object using the following query:

http://courses-staging.umn.edu/campuses/umntc/terms/1149/courses.json/?q=subject_id=JOUR

Other subject_id's work just fine:

http://courses-staging.umn.edu/campuses/umntc/terms/1149/courses.json/?q=subject_id=MATH
http://courses-staging.umn.edu/campuses/umntc/terms/1149/courses.json/?q=subject_id=CSCI

That said, I'm not at all certain that this is a bug -- as a student, I know the [SJMC](http://sjmc.umn.edu) is rather particular about how students must register for their courses -- but I do want to make sure you're aware of it, if you need/wish to be. :) 

Thanks again for all of your work on this! 

Best of luck,

Brandon (a U of M student and web developer with IT@UMN)

**Comment by IanWhitney** [comment]
Very strange. I think there was a problem with our initial data source. We're going to refresh things today and make sure that JOUR classes are there for UMNTC. Thanks for spotting this!

**Comment by IanWhitney** [comment]
We have re-imported data and this problem has been fixed. Thanks @skylineproject for bringing this to our attention!
