### ISSUE TITLE
Track most popular requests, pre-cache them

### ISSUE THREAD

**Issue by IanWhitney** [umn-asr/courses#57]
If we frequently get certain requests we can pre-cache them and handle them super-fast in the future. 

- Track requests over time
- Write a way to find the most popular 10 (?) requests
- After data refresh, run these requests which will put these responses in the HTTP cache

**Comment by IanWhitney** [comment]
I was more interested in this before we fixed the caching performance. Now I'm not sure it's necessary.

Our cache warmer will ensure that the full files are in the Rack Cache. Do we need to make sure that other requests end up in the Rack Cache as soon as we update the data source? Nearly every request takes < 1 second now, so I don't see much value.

**Comment by DebbieGillespie** [comment]
If every request is already < 1 second, I don't think it would be worth the time.
