### ISSUE TITLE
All caps in URL generates 500 error

### ISSUE THREAD

**Issue by DebbieGillespie** [umn-asr/courses#82]
When you visit the following URL:

http://courses.umn.edu/campuses/UMNTC/terms/1159/courses.json

You will get the following error:

{"status":"500","error":"Internal Server Error"}

If you change the campus to umntc, you will get the json output as expected.  Need to update the controller so that it is case insensitive.

**Comment by IanWhitney** [comment]
I think this is fixed by #80 We can check it after the data import is done on Prod.
